"""initial schema

Revision ID: 6b1599cad0b4
Revises: 
Create Date: 2026-09-09 11:55:39.637842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b1599cad0b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_days', mysql.INTEGER(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('price_amount >= 0 AND duration_days > 0', name='ck_plans_values'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index('ix_plans_active_name', ['is_active', 'name', 'id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials_version', mysql.INTEGER(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('disabled_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("category IN ('SUPER_ADMIN','OWNER','EMPLOYEE')", name='ck_users_category'),
    sa.CheckConstraint('credentials_version > 0', name='ck_users_credentials_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_category_active', ['category', 'is_active', 'id'], unique=False)

    op.create_table('bars',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('owner_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('suspended_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('suspension_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED')", name='ck_bars_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bars_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_bars_owner_status', ['owner_id', 'status', 'id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('session_digest', mysql.BINARY(length=32).with_variant(sa.LargeBinary(length=32), "sqlite"), nullable=False),
    sa.Column('csrf_digest', mysql.BINARY(length=32).with_variant(sa.LargeBinary(length=32), "sqlite"), nullable=False),
    sa.Column('credentials_version_snapshot', mysql.INTEGER(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('last_seen_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('revoked_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL AND credentials_version_snapshot IS NULL) OR (user_id IS NOT NULL AND credentials_version_snapshot IS NOT NULL)', name='ck_user_sessions_auth'),
    sa.CheckConstraint('expires_at > created_at', name='ck_user_sessions_dates'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_digest')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_user_sessions_expiry', ['expires_at', 'id'], unique=False)
        batch_op.create_index('ix_user_sessions_user_expiry', ['user_id', 'expires_at', 'id'], unique=False)

    op.create_table('api_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('token_digest', mysql.BINARY(length=32).with_variant(sa.LargeBinary(length=32), "sqlite"), nullable=False),
    sa.Column('family_id', mysql.BINARY(length=16).with_variant(sa.LargeBinary(length=16), "sqlite"), nullable=False),
    sa.Column('rotated_from_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('credentials_version_snapshot', mysql.INTEGER(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('issued_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('last_used_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('expires_at > issued_at', name='ck_api_tokens_dates'),
    sa.ForeignKeyConstraint(['bar_id', 'rotated_from_id'], ['api_tokens.bar_id', 'api_tokens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', 'user_id', name='uq_api_tokens_id_user'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_api_tokens_bar_id_id'),
    sa.UniqueConstraint('token_digest')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_api_tokens_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_bar_id'), ['bar_id'], unique=False)
        batch_op.create_index('ix_api_tokens_family', ['bar_id', 'family_id', 'expires_at', 'id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('target_table', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('request_id', mysql.BINARY(length=16).with_variant(sa.LargeBinary(length=16), "sqlite"), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('occurred_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("(scope = 'BAR' AND bar_id IS NOT NULL) OR (scope = 'PLATFORM' AND bar_id IS NULL)", name='ck_audit_scope'),
    sa.CheckConstraint("outcome IN ('SUCCESS','DENIED')", name='ck_audit_outcome'),
    sa.CheckConstraint('(target_table IS NULL AND target_id IS NULL) OR (target_table IS NOT NULL AND target_id IS NOT NULL)', name='ck_audit_target'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_bar_occurred', ['bar_id', 'occurred_at', 'id'], unique=False)
        batch_op.create_index('ix_audit_request', ['request_id'], unique=False)

    op.create_table('bar_tables',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('capacity', mysql.SMALLINT(unsigned=True).with_variant(sa.SmallInteger(), 'sqlite'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('capacity IS NULL OR capacity > 0', name='ck_bar_tables_capacity'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_bar_tables_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'label', name='uq_bar_tables_label')
    )
    with op.batch_alter_table('bar_tables', schema=None) as batch_op:
        batch_op.create_index('ix_bar_tables_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bar_tables_bar_id'), ['bar_id'], unique=False)

    op.create_table('cash_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('closed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('opened_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('closed_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('expected_closing_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('counted_closing_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('closing_difference', sa.Numeric(precision=19, scale=4), sa.Computed('counted_closing_amount - expected_closing_amount', ), nullable=True),
    sa.Column('open_bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Computed("CASE WHEN status = 'OPEN' THEN bar_id ELSE NULL END", ), nullable=True),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')", name='ck_cash_sessions_status'),
    sa.CheckConstraint('opening_amount >= 0 AND (counted_closing_amount IS NULL OR counted_closing_amount >= 0)', name='ck_cash_sessions_amounts'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_cash_sessions_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_cash_sessions_reference'),
    sa.UniqueConstraint('open_bar_id', name='uq_cash_sessions_open_bar')
    )
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_cash_sessions_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_sessions_bar_id'), ['bar_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_customers_bar_id_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_bar_id'), ['bar_id'], unique=False)
        batch_op.create_index('ix_customers_name', ['bar_id', 'display_name', 'id'], unique=False)

    op.create_table('expense_categories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_expense_categories_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'name', name='uq_expense_categories_name')
    )
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.create_index('ix_expense_categories_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_categories_bar_id'), ['bar_id'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', mysql.VARBINARY(length=128).with_variant(sa.LargeBinary(length=128), "sqlite"), nullable=False),
    sa.Column('request_hash', mysql.BINARY(length=32).with_variant(sa.LargeBinary(length=32), "sqlite"), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response_status', mysql.SMALLINT(unsigned=True).with_variant(sa.SmallInteger(), 'sqlite'), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("status IN ('PROCESSING','COMPLETED')", name='ck_idempotency_status'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'actor_id', 'operation', 'idempotency_key', name='uq_idempotency_actor_key'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_idempotency_records_bar_id_id')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_completed', ['bar_id', 'completed_at', 'id'], unique=False)
        batch_op.create_index('ix_idempotency_records_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_records_bar_id'), ['bar_id'], unique=False)

    op.create_table('inventories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('counted_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('posted_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('cancelled_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','POSTED','CANCELLED')", name='ck_inventories_status'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_inventories_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_inventories_reference')
    )
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.create_index('ix_inventories_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventories_bar_id'), ['bar_id'], unique=False)

    op.create_table('product_categories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_product_categories_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'name', name='uq_product_categories_name')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index('ix_product_categories_active_name', ['bar_id', 'is_active', 'name', 'id'], unique=False)
        batch_op.create_index('ix_product_categories_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_bar_id'), ['bar_id'], unique=False)

    op.create_table('staff_assignments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('ended_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('active_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Computed('CASE WHEN ended_at IS NULL THEN user_id ELSE NULL END', ), nullable=True),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("role IN ('BAR_ADMIN','CASHIER','SERVER')", name='ck_staff_role'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_staff_dates'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_user_id', name='uq_staff_assignments_active_user'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_staff_assignments_bar_id_id')
    )
    with op.batch_alter_table('staff_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_staff_assignments_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_assignments_bar_id'), ['bar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_assignments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_staff_bar_role_ended', ['bar_id', 'role', 'ended_at', 'id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan_code_snapshot', sa.String(length=32), nullable=False),
    sa.Column('plan_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('price_amount_snapshot', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('duration_days_snapshot', mysql.INTEGER(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('starts_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('ends_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('activated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('expired_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('cancelled_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('active_bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Computed("CASE WHEN status = 'ACTIVE' THEN bar_id ELSE NULL END", ), nullable=True),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','ACTIVE','EXPIRED','CANCELLED') AND price_amount_snapshot >= 0 AND duration_days_snapshot > 0 AND ends_at > starts_at", name='ck_subscriptions_values'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_bar_id', name='uq_subscriptions_active_bar'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_subscriptions_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_subscriptions_reference')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_bar_id'), ['bar_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_suppliers_bar_id_id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('ix_suppliers_active_name', ['bar_id', 'is_active', 'name', 'id'], unique=False)
        batch_op.create_index('ix_suppliers_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_bar_id'), ['bar_id'], unique=False)

    op.create_table('cash_handovers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('staff_assignment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('cash_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('received_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('posted_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('cancelled_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("amount > 0 AND status IN ('DRAFT','POSTED','CANCELLED')", name='ck_cash_handovers_values'),
    sa.ForeignKeyConstraint(['bar_id', 'cash_session_id'], ['cash_sessions.bar_id', 'cash_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'staff_assignment_id'], ['staff_assignments.bar_id', 'staff_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', 'staff_assignment_id', name='uq_cash_handovers_id_staff'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_cash_handovers_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_cash_handovers_reference')
    )
    with op.batch_alter_table('cash_handovers', schema=None) as batch_op:
        batch_op.create_index('ix_cash_handovers_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_handovers_bar_id'), ['bar_id'], unique=False)

    op.create_table('cash_movements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('cash_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount_delta', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('refund_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('supplier_payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('expense_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('cash_handover_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reversal_of_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('manual_kind', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('amount_delta <> 0', name='ck_cash_movements_amount'),
    sa.ForeignKeyConstraint(['bar_id', 'cash_session_id'], ['cash_sessions.bar_id', 'cash_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'cash_handover_id', name='uq_cash_movements_handover'),
    sa.UniqueConstraint('bar_id', 'expense_id', name='uq_cash_movements_expense'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_cash_movements_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'payment_id', name='uq_cash_movements_payment'),
    sa.UniqueConstraint('bar_id', 'refund_id', name='uq_cash_movements_refund'),
    sa.UniqueConstraint('bar_id', 'reversal_of_id', name='uq_cash_movements_reversal'),
    sa.UniqueConstraint('bar_id', 'supplier_payment_id', name='uq_cash_movements_supplier_payment')
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index('ix_cash_movements_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_bar_id'), ['bar_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('expense_category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entry_kind', sa.String(length=16), nullable=False),
    sa.Column('reversal_of_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('cash_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('incurred_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("amount > 0 AND entry_kind IN ('EXPENSE','REVERSAL')", name='ck_expenses_values'),
    sa.ForeignKeyConstraint(['bar_id', 'cash_session_id'], ['cash_sessions.bar_id', 'cash_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'expense_category_id'], ['expense_categories.bar_id', 'expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_expenses_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_expenses_reference'),
    sa.UniqueConstraint('bar_id', 'reversal_of_id', name='uq_expenses_reversal')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expenses_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_bar_id'), ['bar_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('table_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('assigned_staff_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_name_snapshot', sa.String(length=160), nullable=True),
    sa.Column('table_label_snapshot', sa.String(length=64), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('posted_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('closed_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('cancelled_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','POSTED','CLOSED','CANCELLED')", name='ck_orders_status'),
    sa.CheckConstraint('subtotal_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND discount_amount <= subtotal_amount AND total_amount = subtotal_amount-discount_amount+tax_amount', name='ck_orders_amounts'),
    sa.ForeignKeyConstraint(['bar_id', 'assigned_staff_id'], ['staff_assignments.bar_id', 'staff_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'customer_id'], ['customers.bar_id', 'customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'table_id'], ['bar_tables.bar_id', 'bar_tables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_orders_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_orders_reference')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_bar_id'), ['bar_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('base_unit', sa.String(length=16), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('valuation_unit_cost', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('sale_price >= 0 AND valuation_unit_cost >= 0', name='ck_products_prices'),
    sa.ForeignKeyConstraint(['bar_id', 'category_id'], ['product_categories.bar_id', 'product_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_products_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'sku', name='uq_products_sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_bar_category_active', ['bar_id', 'category_id', 'is_active', 'id'], unique=False)
        batch_op.create_index('ix_products_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_bar_id'), ['bar_id'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('supplier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('supplier_invoice_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('supplier_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('posted_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('cancelled_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','POSTED','CANCELLED')", name='ck_purchases_status'),
    sa.CheckConstraint('subtotal_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount = subtotal_amount - discount_amount + tax_amount AND discount_amount <= subtotal_amount', name='ck_purchases_amounts'),
    sa.ForeignKeyConstraint(['bar_id', 'supplier_id'], ['suppliers.bar_id', 'suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_purchases_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_purchases_reference')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index('ix_purchases_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_bar_id'), ['bar_id'], unique=False)

    op.create_table('staff_cash_ledgers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('staff_assignment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount_delta', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('refund_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('cash_handover_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reversal_of_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('occurred_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('amount_delta <> 0', name='ck_staff_ledger_amount'),
    sa.ForeignKeyConstraint(['bar_id', 'staff_assignment_id'], ['staff_assignments.bar_id', 'staff_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'cash_handover_id', name='uq_staff_ledger_handover'),
    sa.UniqueConstraint('bar_id', 'id', 'staff_assignment_id', name='uq_staff_ledger_id_staff'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_staff_cash_ledgers_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'payment_id', name='uq_staff_ledger_payment'),
    sa.UniqueConstraint('bar_id', 'refund_id', name='uq_staff_ledger_refund'),
    sa.UniqueConstraint('bar_id', 'reversal_of_id', name='uq_staff_ledger_reversal')
    )
    with op.batch_alter_table('staff_cash_ledgers', schema=None) as batch_op:
        batch_op.create_index('ix_staff_cash_ledgers_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_cash_ledgers_bar_id'), ['bar_id'], unique=False)

    op.create_table('subscription_payments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('subscription_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entry_kind', sa.String(length=16), nullable=False),
    sa.Column('reversal_of_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=False),
    sa.Column('paid_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("amount > 0 AND entry_kind IN ('PAYMENT','REVERSAL')", name='ck_subscription_payments_values'),
    sa.ForeignKeyConstraint(['bar_id', 'reversal_of_id'], ['subscription_payments.bar_id', 'subscription_payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'subscription_id'], ['subscriptions.bar_id', 'subscriptions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_subscription_payments_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_subscription_payments_reference'),
    sa.UniqueConstraint('bar_id', 'reversal_of_id', name='uq_subscription_payments_reversal'),
    sa.UniqueConstraint('provider_code', 'provider_transaction_id', name='uq_subscription_payments_provider')
    )
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.create_index('ix_subscription_payments_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_payments_bar_id'), ['bar_id'], unique=False)

    op.create_table('token_revocations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('api_token_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revoked_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id', 'api_token_id'], ['api_tokens.bar_id', 'api_tokens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'api_token_id', name='uq_token_revocations_token'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_token_revocations_bar_id_id')
    )
    with op.batch_alter_table('token_revocations', schema=None) as batch_op:
        batch_op.create_index('ix_token_revocations_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_revocations_bar_id'), ['bar_id'], unique=False)

    op.create_table('inventory_lines',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('inventory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('expected_quantity_snapshot', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('balance_version_snapshot', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('difference_quantity', sa.Numeric(precision=20, scale=6), sa.Computed('counted_quantity - expected_quantity_snapshot', ), nullable=True),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('counted_quantity IS NULL OR counted_quantity >= 0', name='ck_inventory_lines_counted'),
    sa.ForeignKeyConstraint(['bar_id', 'inventory_id'], ['inventories.bar_id', 'inventories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'product_id'], ['products.bar_id', 'products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', 'product_id', name='uq_inventory_lines_id_product'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_inventory_lines_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'inventory_id', 'product_id', name='uq_inventory_lines_product')
    )
    with op.batch_alter_table('inventory_lines', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_lines_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_lines_bar_id'), ['bar_id'], unique=False)

    op.create_table('order_lines',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', mysql.INTEGER(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit_sale_price_snapshot', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('line_no > 0 AND quantity > 0 AND unit_sale_price_snapshot >= 0 AND unit_cost_snapshot >= 0 AND subtotal_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND discount_amount <= subtotal_amount AND total_amount = subtotal_amount-discount_amount+tax_amount', name='ck_order_lines_amounts'),
    sa.ForeignKeyConstraint(['bar_id', 'order_id'], ['orders.bar_id', 'orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'product_id'], ['products.bar_id', 'products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', 'product_id', name='uq_order_lines_id_product'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_order_lines_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'order_id', 'id', name='uq_order_lines_order_id'),
    sa.UniqueConstraint('bar_id', 'order_id', 'line_no', name='uq_order_lines_no')
    )
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.create_index('ix_order_lines_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_lines_bar_id'), ['bar_id'], unique=False)

    op.create_table('order_returns',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('posted_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('cancelled_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=True),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','POSTED','CANCELLED') AND total_amount >= 0", name='ck_order_returns_values'),
    sa.ForeignKeyConstraint(['bar_id', 'order_id'], ['orders.bar_id', 'orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_order_returns_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'order_id', 'id', name='uq_order_returns_order_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_order_returns_reference')
    )
    with op.batch_alter_table('order_returns', schema=None) as batch_op:
        batch_op.create_index('ix_order_returns_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_returns_bar_id'), ['bar_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('cash_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('cash_holder', sa.String(length=16), nullable=True),
    sa.Column('staff_assignment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('received_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("amount > 0 AND method IN ('CASH','MOBILE_MONEY','CARD','BANK_TRANSFER')", name='ck_payments_values'),
    sa.ForeignKeyConstraint(['bar_id', 'cash_session_id'], ['cash_sessions.bar_id', 'cash_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'order_id'], ['orders.bar_id', 'orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'staff_assignment_id'], ['staff_assignments.bar_id', 'staff_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_payments_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'order_id', 'id', name='uq_payments_order_id'),
    sa.UniqueConstraint('bar_id', 'provider_code', 'provider_transaction_id', name='uq_payments_provider'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_payments_reference')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_bar_id'), ['bar_id'], unique=False)

    op.create_table('purchase_lines',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('purchase_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', mysql.INTEGER(unsigned=True).with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('line_no > 0 AND quantity > 0 AND unit_cost_snapshot >= 0 AND subtotal_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND discount_amount <= subtotal_amount AND total_amount = subtotal_amount-discount_amount+tax_amount', name='ck_purchase_lines_amounts'),
    sa.ForeignKeyConstraint(['bar_id', 'product_id'], ['products.bar_id', 'products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'purchase_id'], ['purchases.bar_id', 'purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', 'product_id', name='uq_purchase_lines_id_product'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_purchase_lines_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'purchase_id', 'line_no', name='uq_purchase_lines_no')
    )
    with op.batch_alter_table('purchase_lines', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_lines_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_lines_bar_id'), ['bar_id'], unique=False)

    op.create_table('stock_balances',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('version', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id', 'product_id'], ['products.bar_id', 'products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_stock_balances_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'product_id', name='uq_stock_balances_product')
    )
    with op.batch_alter_table('stock_balances', schema=None) as batch_op:
        batch_op.create_index('ix_stock_balances_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_balances_bar_id'), ['bar_id'], unique=False)

    op.create_table('supplier_payments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('purchase_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entry_kind', sa.String(length=16), nullable=False),
    sa.Column('reversal_of_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('cash_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('paid_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("amount > 0 AND entry_kind IN ('PAYMENT','REVERSAL')", name='ck_supplier_payments_values'),
    sa.ForeignKeyConstraint(['bar_id', 'cash_session_id'], ['cash_sessions.bar_id', 'cash_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'purchase_id'], ['purchases.bar_id', 'purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'reversal_of_id'], ['supplier_payments.bar_id', 'supplier_payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_supplier_payments_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_supplier_payments_reference'),
    sa.UniqueConstraint('bar_id', 'reversal_of_id', name='uq_supplier_payments_reversal')
    )
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_index('ix_supplier_payments_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_payments_bar_id'), ['bar_id'], unique=False)

    op.create_table('order_return_lines',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_return_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('restock_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('quantity > 0 AND restock_quantity >= 0 AND restock_quantity <= quantity AND credit_amount >= 0', name='ck_order_return_lines_values'),
    sa.ForeignKeyConstraint(['bar_id', 'order_id'], ['orders.bar_id', 'orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'order_line_id'], ['order_lines.bar_id', 'order_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'order_return_id'], ['order_returns.bar_id', 'order_returns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'product_id'], ['products.bar_id', 'products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', 'product_id', name='uq_order_return_lines_id_product'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_order_return_lines_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'order_return_id', 'order_line_id', name='uq_order_return_lines_source')
    )
    with op.batch_alter_table('order_return_lines', schema=None) as batch_op:
        batch_op.create_index('ix_order_return_lines_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_return_lines_bar_id'), ['bar_id'], unique=False)

    op.create_table('refunds',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_return_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('cash_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('cash_holder', sa.String(length=16), nullable=True),
    sa.Column('staff_assignment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('refunded_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint("amount > 0 AND method IN ('CASH','MOBILE_MONEY','CARD','BANK_TRANSFER')", name='ck_refunds_values'),
    sa.ForeignKeyConstraint(['bar_id', 'cash_session_id'], ['cash_sessions.bar_id', 'cash_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'order_id'], ['orders.bar_id', 'orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'order_return_id'], ['order_returns.bar_id', 'order_returns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'payment_id'], ['payments.bar_id', 'payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'staff_assignment_id'], ['staff_assignments.bar_id', 'staff_assignments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_refunds_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'provider_code', 'provider_transaction_id', name='uq_refunds_provider'),
    sa.UniqueConstraint('bar_id', 'reference', name='uq_refunds_reference')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index('ix_refunds_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_bar_id'), ['bar_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=16), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('purchase_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('order_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('order_return_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('inventory_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reversal_of_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('manual_kind', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6).with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.CheckConstraint('quantity_delta <> 0 AND unit_cost_snapshot >= 0', name='ck_stock_movement_values'),
    sa.ForeignKeyConstraint(['bar_id', 'inventory_line_id'], ['inventory_lines.bar_id', 'inventory_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'order_line_id'], ['order_lines.bar_id', 'order_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'order_return_line_id'], ['order_return_lines.bar_id', 'order_return_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'product_id'], ['products.bar_id', 'products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'purchase_line_id'], ['purchase_lines.bar_id', 'purchase_lines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id', 'reversal_of_id'], ['stock_movements.bar_id', 'stock_movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_id', 'id', name='uq_stock_movements_bar_id_id'),
    sa.UniqueConstraint('bar_id', 'inventory_line_id', name='uq_stock_inventory_line'),
    sa.UniqueConstraint('bar_id', 'order_line_id', name='uq_stock_order_line'),
    sa.UniqueConstraint('bar_id', 'order_return_line_id', name='uq_stock_return_line'),
    sa.UniqueConstraint('bar_id', 'purchase_line_id', name='uq_stock_purchase_line'),
    sa.UniqueConstraint('bar_id', 'reversal_of_id', name='uq_stock_reversal')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movements_bar_created', ['bar_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_bar_id'), ['bar_id'], unique=False)
        batch_op.create_index('ix_stock_movements_product_time', ['bar_id', 'product_id', 'occurred_at', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError(
        "Refusing destructive downgrade of the initial Bar Manager Pro schema. "
        "Create an explicit, reviewed data-retention migration instead."
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_product_time')
        batch_op.drop_index(batch_op.f('ix_stock_movements_bar_id'))
        batch_op.drop_index('ix_stock_movements_bar_created')

    op.drop_table('stock_movements')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_bar_id'))
        batch_op.drop_index('ix_refunds_bar_created')

    op.drop_table('refunds')
    with op.batch_alter_table('order_return_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_return_lines_bar_id'))
        batch_op.drop_index('ix_order_return_lines_bar_created')

    op.drop_table('order_return_lines')
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_payments_bar_id'))
        batch_op.drop_index('ix_supplier_payments_bar_created')

    op.drop_table('supplier_payments')
    with op.batch_alter_table('stock_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_balances_bar_id'))
        batch_op.drop_index('ix_stock_balances_bar_created')

    op.drop_table('stock_balances')
    with op.batch_alter_table('purchase_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_lines_bar_id'))
        batch_op.drop_index('ix_purchase_lines_bar_created')

    op.drop_table('purchase_lines')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_bar_id'))
        batch_op.drop_index('ix_payments_bar_created')

    op.drop_table('payments')
    with op.batch_alter_table('order_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_returns_bar_id'))
        batch_op.drop_index('ix_order_returns_bar_created')

    op.drop_table('order_returns')
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_lines_bar_id'))
        batch_op.drop_index('ix_order_lines_bar_created')

    op.drop_table('order_lines')
    with op.batch_alter_table('inventory_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_lines_bar_id'))
        batch_op.drop_index('ix_inventory_lines_bar_created')

    op.drop_table('inventory_lines')
    with op.batch_alter_table('token_revocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_revocations_bar_id'))
        batch_op.drop_index('ix_token_revocations_bar_created')

    op.drop_table('token_revocations')
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_payments_bar_id'))
        batch_op.drop_index('ix_subscription_payments_bar_created')

    op.drop_table('subscription_payments')
    with op.batch_alter_table('staff_cash_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_cash_ledgers_bar_id'))
        batch_op.drop_index('ix_staff_cash_ledgers_bar_created')

    op.drop_table('staff_cash_ledgers')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_bar_id'))
        batch_op.drop_index('ix_purchases_bar_created')

    op.drop_table('purchases')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_bar_id'))
        batch_op.drop_index('ix_products_bar_created')
        batch_op.drop_index('ix_products_bar_category_active')

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_bar_id'))
        batch_op.drop_index('ix_orders_bar_created')

    op.drop_table('orders')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_bar_id'))
        batch_op.drop_index('ix_expenses_bar_created')

    op.drop_table('expenses')
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movements_bar_id'))
        batch_op.drop_index('ix_cash_movements_bar_created')

    op.drop_table('cash_movements')
    with op.batch_alter_table('cash_handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_handovers_bar_id'))
        batch_op.drop_index('ix_cash_handovers_bar_created')

    op.drop_table('cash_handovers')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_bar_id'))
        batch_op.drop_index('ix_suppliers_bar_created')
        batch_op.drop_index('ix_suppliers_active_name')

    op.drop_table('suppliers')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_bar_id'))
        batch_op.drop_index('ix_subscriptions_bar_created')

    op.drop_table('subscriptions')
    with op.batch_alter_table('staff_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_bar_role_ended')
        batch_op.drop_index(batch_op.f('ix_staff_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_assignments_bar_id'))
        batch_op.drop_index('ix_staff_assignments_bar_created')

    op.drop_table('staff_assignments')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_bar_id'))
        batch_op.drop_index('ix_product_categories_bar_created')
        batch_op.drop_index('ix_product_categories_active_name')

    op.drop_table('product_categories')
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventories_bar_id'))
        batch_op.drop_index('ix_inventories_bar_created')

    op.drop_table('inventories')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_bar_id'))
        batch_op.drop_index('ix_idempotency_records_bar_created')
        batch_op.drop_index('ix_idempotency_completed')

    op.drop_table('idempotency_records')
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_categories_bar_id'))
        batch_op.drop_index('ix_expense_categories_bar_created')

    op.drop_table('expense_categories')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_name')
        batch_op.drop_index(batch_op.f('ix_customers_bar_id'))
        batch_op.drop_index('ix_customers_bar_created')

    op.drop_table('customers')
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sessions_bar_id'))
        batch_op.drop_index('ix_cash_sessions_bar_created')

    op.drop_table('cash_sessions')
    with op.batch_alter_table('bar_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bar_tables_bar_id'))
        batch_op.drop_index('ix_bar_tables_bar_created')

    op.drop_table('bar_tables')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_request')
        batch_op.drop_index('ix_audit_bar_occurred')

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_api_tokens_family')
        batch_op.drop_index(batch_op.f('ix_api_tokens_bar_id'))
        batch_op.drop_index('ix_api_tokens_bar_created')

    op.drop_table('api_tokens')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_expiry')
        batch_op.drop_index('ix_user_sessions_expiry')

    op.drop_table('user_sessions')
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_index('ix_bars_owner_status')
        batch_op.drop_index(batch_op.f('ix_bars_owner_id'))

    op.drop_table('bars')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_category_active')

    op.drop_table('users')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index('ix_plans_active_name')

    op.drop_table('plans')
    # ### end Alembic commands ###
